"use strict";

const Module = require("module");
const { DAY_TRIAL_URL, SINGLE_SYSTEM_PRICE_MONTHLY, THREE_SYSTEM_BUNDLE_PRICE_MONTHLY } = require("./lib/website-commercial-offer");

const DAY_PATH = "/trading-systems/day-trading";
const ACCESS_PATH = "/access";
const SERVICES_PATH = "/services";
const STYLE_ID = "vx-conversion-access-services-style";
const MARKER = "data-vx-conversion-access-services";
const SUPPORTED_PATHS = new Set([DAY_PATH, ACCESS_PATH, SERVICES_PATH]);

function escapeRegex(value){return String(value).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");}
function tagRange(html,tag,start){if(start<0)return null;const openEnd=html.indexOf(">",start);if(openEnd<0)return null;const re=new RegExp(`<\\/?${escapeRegex(tag)}\\b[^>]*>`,"gi");re.lastIndex=start;let depth=0,m;while((m=re.exec(html))){depth+=new RegExp(`^<\\/${escapeRegex(tag)}\\b`,"i").test(m[0])?-1:1;if(depth===0)return{start,end:re.lastIndex,openEnd:openEnd+1,closeStart:m.index};}return null;}
function prependMain(html,inner){const s=String(html||"").search(/<main\b/i),r=tagRange(html,"main",s);return r?html.slice(0,r.openEnd)+`\n${inner}\n`+html.slice(r.openEnd):html;}
function appendBeforeMainClose(html,inner){const s=String(html||"").search(/<main\b/i),r=tagRange(html,"main",s);return r?html.slice(0,r.closeStart)+`\n${inner}\n`+html.slice(r.closeStart):html;}

function renderTelegramExample(){return `<section class="vx-conversion-telegram-example" ${MARKER}="telegram-example" aria-labelledby="vx-telegram-example-title"><div class="vx-conversion-as-wrap"><div class="vx-conversion-as-kicker">DAY TRADING TELEGRAM</div><h2 id="vx-telegram-example-title">What a Day Trading signal looks like.</h2><p class="vx-conversion-as-lead">This is an illustrative format using placeholders — not a live trade, recommendation, ticker, price, target, or result. It mirrors fields used by the current Vixale Prime open-signal formatter.</p><div class="vx-telegram-example-grid"><pre aria-label="Illustrative Day Trading Telegram signal">🟢 <b>Vixale Prime opened LONG</b>

<b>[TICKER]</b>
📍 Entry: <b>[entry]</b>
🎯 Target: <b>[target]</b>
🛑 Stop Ref: <b>[stop]</b></pre><div class="vx-telegram-example-notes"><strong>Day Trading signals only</strong><p>The 30-day trial applies to Day Trading Telegram signals. Swing Trading and Options remain website-update products in this release.</p><a href="${DAY_TRIAL_URL}" target="_blank" rel="noopener noreferrer">Request 30-Day Trial</a></div></div></div></section>`;}

function renderAccessIntro(system=""){const label=system==="options"?"Options":system==="day-trading"?"Day Trading":"Vixale";return `<section class="vx-conversion-access-intro" ${MARKER}="access"><div class="vx-conversion-as-wrap"><div class="vx-conversion-as-kicker">VIEWER ACCESS</div><h1>Request free read-only viewer access.</h1><p class="vx-conversion-as-lead">${label} viewer access is for protected website detail. It is separate from the 30-day Day Trading Telegram signals trial and separate from the $${SINGLE_SYSTEM_PRICE_MONTHLY}/month or $${THREE_SYSTEM_BUNDLE_PRICE_MONTHLY}/month subscription request.</p><div class="vx-access-paths"><article><strong>Viewer access</strong><span>Free · read-only · email verification · manual review</span><b>Use the request form below.</b></article><article><strong>Day Trading Telegram trial</strong><span>30 days · Day Trading signals only</span><a href="${DAY_TRIAL_URL}" target="_blank" rel="noopener noreferrer">Request trial →</a></article><article><strong>Paid system plans</strong><span>$${SINGLE_SYSTEM_PRICE_MONTHLY}/month single · $${THREE_SYSTEM_BUNDLE_PRICE_MONTHLY}/month all three</span><a href="/pricing">Compare pricing →</a></article></div><p class="vx-access-form-cue">Viewer request form ↓</p></div></section>`;}

function renderServicesIntro(){return `<section class="vx-conversion-services-intro" ${MARKER}="services"><div class="vx-conversion-as-wrap"><div class="vx-conversion-as-kicker">CUSTOM SERVICES</div><h1>Need setup, automation, strategy work, or a custom bot?</h1><p class="vx-conversion-as-lead">Services are scoped custom work. They are separate from the $${SINGLE_SYSTEM_PRICE_MONTHLY}/month Single System subscription, the $${THREE_SYSTEM_BUNDLE_PRICE_MONTHLY}/month Three-System Bundle, and free viewer access.</p><div class="vx-services-separation"><div><strong>Trading-system subscriptions</strong><span>Day Trading, Swing Trading, or Options</span><a href="/pricing">View Pricing →</a></div><div><strong>Custom Services</strong><span>Signals &amp; Research · Automation / Setup · Strategy Review / Development · Custom Bot / Integration</span><b>Choose the matching service form below.</b></div></div></div></section>`;}

const styles=`<style id="${STYLE_ID}">
.vx-conversion-as-wrap{max-width:1160px;margin:0 auto;padding:0 24px;box-sizing:border-box}.vx-conversion-as-kicker{color:#287153;font-size:10.5px;font-weight:800;letter-spacing:.09em;text-transform:uppercase}.vx-conversion-as-lead{max-width:820px;margin:12px 0 0;color:#5f6d67;font-size:14.5px;line-height:1.6}.vx-conversion-telegram-example{padding:30px 0 44px;background:#f6faf8;border-top:1px solid #dfe7e2}.vx-conversion-telegram-example h2,.vx-conversion-services-intro h1,.vx-conversion-access-intro h1{max-width:820px;margin:8px 0 0;color:#17211d;font-size:clamp(30px,4vw,46px);font-weight:540;line-height:1.06;letter-spacing:-.035em}.vx-telegram-example-grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(0,.85fr);gap:14px;margin-top:20px}.vx-telegram-example-grid pre{margin:0;padding:22px;border:1px solid #163f30;border-radius:18px;background:#102f24;color:#f4faf7;font:13px/1.7 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap}.vx-telegram-example-notes{padding:21px;border:1px solid #dce6e1;border-radius:18px;background:#fff}.vx-telegram-example-notes strong{font-size:16px}.vx-telegram-example-notes p{margin:8px 0 0;color:#5f6d67;font-size:13px;line-height:1.55}.vx-telegram-example-notes a,.vx-services-separation a,.vx-access-paths a{display:inline-flex;margin-top:14px;color:#176442;font-size:12.5px;font-weight:750;text-decoration:none}.vx-conversion-access-intro,.vx-conversion-services-intro{padding:38px 0 30px;background:linear-gradient(180deg,#f4faf6,#fff);border-bottom:1px solid #dfe7e2}.vx-access-paths{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:20px}.vx-access-paths article,.vx-services-separation>div{padding:17px;border:1px solid #dce6e1;border-radius:16px;background:#fff}.vx-access-paths strong,.vx-services-separation strong{display:block;font-size:13.5px}.vx-access-paths span,.vx-services-separation span{display:block;margin-top:5px;color:#65716c;font-size:12px;line-height:1.45}.vx-access-paths b,.vx-services-separation b{display:block;margin-top:13px;color:#176442;font-size:11.5px}.vx-access-form-cue{margin:17px 0 0;color:#176442;font-size:12px;font-weight:750}.vx-services-separation{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:20px}@media(max-width:760px){.vx-conversion-as-wrap{padding:0 16px}.vx-telegram-example-grid,.vx-access-paths,.vx-services-separation{grid-template-columns:1fr}.vx-conversion-access-intro,.vx-conversion-services-intro{padding-top:28px}.vx-telegram-example-grid pre{font-size:12px}}
</style>`;
function injectStyles(html){if(html.includes(`id="${STYLE_ID}"`))return html;return html.includes("</head>")?html.replace("</head>",`${styles}\n</head>`):`${styles}${html}`;}
function refineDay(html){if(html.includes(`${MARKER}="telegram-example"`))return html;return injectStyles(appendBeforeMainClose(html,renderTelegramExample()));}
function refineAccess(html,system){if(html.includes(`${MARKER}="access"`))return html;return injectStyles(prependMain(html,renderAccessIntro(system)));}
function refineServices(html){if(html.includes(`${MARKER}="services"`))return html;return injectStyles(prependMain(html,renderServicesIntro()));}
function refine(html,path,system=""){if(typeof html!=="string")return html;if(path===DAY_PATH)return refineDay(html);if(path===ACCESS_PATH)return refineAccess(html,system);if(path===SERVICES_PATH)return refineServices(html);return html;}
function install(app){app.use((req,res,next)=>{const method=String(req.method||"GET").toUpperCase(),path=String(req.path||req.url||"/").split("?")[0];if((method!=="GET"&&method!=="HEAD")||!SUPPORTED_PATHS.has(path))return next();const send=res.send.bind(res);res.send=function(body){const type=String(res.getHeader?.("Content-Type")||"");if(typeof body==="string"&&(!type||type.includes("html"))&&res.statusCode<300)body=refine(body,path,req.query&&req.query.system);return send(body)};return next()});}
function copyExpressStatics(target,source){for(const key of Reflect.ownKeys(source)){if(["length","name","prototype","arguments","caller"].includes(String(key)))continue;const d=Object.getOwnPropertyDescriptor(source,key);if(d)try{Object.defineProperty(target,key,d)}catch(_){}}Object.setPrototypeOf(target,Object.getPrototypeOf(source))}
function wrapExpress(factory){if(typeof factory!=="function"||factory.__vixaleConversionAccessServicesWrapped)return factory;function wrapped(...args){const app=factory(...args);install(app);return app}copyExpressStatics(wrapped,factory);Object.defineProperty(wrapped,"__vixaleConversionAccessServicesWrapped",{value:true});return wrapped}
const originalLoad=Module._load;Module._load=function(request,parent,isMain){const loaded=originalLoad.call(this,request,parent,isMain);return request==="express"?wrapExpress(loaded):loaded};
module.exports={DAY_PATH,ACCESS_PATH,SERVICES_PATH,STYLE_ID,MARKER,SUPPORTED_PATHS,tagRange,prependMain,appendBeforeMainClose,renderTelegramExample,renderAccessIntro,renderServicesIntro,injectStyles,refineDay,refineAccess,refineServices,refine,install,wrapExpress};
