"use strict";

const Module = require("module");

const RU_HOST = "ru.vixale.com";
const EN_HOST = "www.vixale.com";
const LOCALE = "ru";
const PRIVATE_PREFIXES = Object.freeze([
  "/admin",
  "/tv",
  "/ib/",
  "/api/",
  "/webhook",
]);

// The Russian site deliberately reuses the final English HTML so structure, CSS,
// responsive behavior, live-data wiring, forms and authorization remain identical.
// Only user-facing copy and locale metadata are transformed here.
const TRANSLATIONS = Object.freeze([
  ...require("./website_russian_translations_1"),
  ...require("./website_russian_translations_2"),
  ...require("./website_russian_translations_3"),
]);

const ATTRIBUTE_NAMES = new Set(["placeholder", "aria-label", "title", "alt", "content"]);
const SORTED_TRANSLATIONS = Object.freeze([...TRANSLATIONS].sort((a, b) => b[0].length - a[0].length));

function normalizeHost(value) {
  return String(value || "")
    .split(",")[0]
    .trim()
    .toLowerCase()
    .replace(/:\d+$/, "");
}

function isRussianHost(value) {
  return normalizeHost(value) === RU_HOST;
}

function pathnameOf(req) {
  return String(req?.originalUrl || req?.url || "/").split("?")[0] || "/";
}

function isLocalizablePath(pathname) {
  const path = String(pathname || "/");
  return !PRIVATE_PREFIXES.some(prefix => path === prefix || path.startsWith(prefix));
}

function preserveCase(source, translated) {
  if (!source || !translated) return translated;
  if (source.toUpperCase() === source && /[A-Z]/.test(source)) return translated.toUpperCase();
  return translated;
}

function translateChunk(value) {
  let out = String(value ?? "");
  if (!/[A-Za-z]/.test(out)) return out;
  for (const [english, russian] of SORTED_TRANSLATIONS) {
    if (!out.includes(english)) continue;
    out = out.split(english).join(preserveCase(english, russian));
  }
  return out;
}

function translateAttributes(tag) {
  if (!/[A-Za-z]/.test(tag)) return tag;
  return tag.replace(/\b([a-zA-Z:-]+)=("([^"]*)"|'([^']*)')/g, (full, rawName, quoted, doubleValue, singleValue) => {
    const name = String(rawName || "").toLowerCase();
    if (!ATTRIBUTE_NAMES.has(name)) return full;
    const value = doubleValue !== undefined ? doubleValue : singleValue;
    const translated = translateChunk(value);
    if (translated === value) return full;
    const quote = quoted[0];
    return `${rawName}=${quote}${translated}${quote}`;
  });
}

function localizeSeoHosts(html, pathname) {
  const protectedBlocks = [];
  let out = String(html).replace(/<(script|style|pre|code|textarea)\b[^>]*>[\s\S]*?<\/\1>/gi, block => {
    const token = `\u0000VXRUHOST${protectedBlocks.length}\u0000`;
    protectedBlocks.push(block);
    return token;
  });

  // Remove only alternates generated by this layer before rebuilding them. This
  // keeps repeated passes idempotent while preserving any unrelated SEO tags.
  out = out.replace(/\s*<link\b[^>]*data-vx-ru-hreflang=["']1["'][^>]*>\s*/gi, "\n");
  out = out.replace(/\s*<link\b[^>]*data-vx-ru-hreflang=["']ru["'][^>]*>\s*/gi, "\n");
  out = out.replace(/\s*<link\b[^>]*data-vx-ru-hreflang=["']x-default["'][^>]*>\s*/gi, "\n");

  out = out
    .replace(/https:\/\/www\.vixale\.com(?=\/|["'\s<])/gi, `https://${RU_HOST}`)
    .replace(/https:\/\/vixale\.com(?=\/|["'\s<])/gi, `https://${RU_HOST}`);

  // Public-QA can emit an English canonical before this final RU layer, so the
  // RU canonical is corrected above and alternates make the locale relationship explicit.
  if (/<\/head>/i.test(out)) {
    const path = pathname === "/" ? "/" : pathname;
    const alternates = [
      `<link data-vx-ru-hreflang="1" rel="alternate" hreflang="en" href="https://${EN_HOST}${path}">`,
      `<link data-vx-ru-hreflang="ru" rel="alternate" hreflang="ru" href="https://${RU_HOST}${path}">`,
      `<link data-vx-ru-hreflang="x-default" rel="alternate" hreflang="x-default" href="https://${EN_HOST}${path}">`,
    ].join("\n");
    out = out.replace(/<\/head>/i, `${alternates}\n</head>`);
  }

  out = out.replace(/\u0000VXRUHOST(\d+)\u0000/g, (_, index) => protectedBlocks[Number(index)] || "");
  return out;
}

function translateHtmlText(html) {
  const source = String(html ?? "");
  // Keep script/style/pre/code/textarea bodies byte-for-byte unchanged. This is
  // critical because presentation text can sit next to live-data and form logic.
  const protectedBlocks = [];
  let masked = source.replace(/<(script|style|pre|code|textarea)\b[^>]*>[\s\S]*?<\/\1>/gi, block => {
    const token = `\u0000VXRU${protectedBlocks.length}\u0000`;
    protectedBlocks.push(block);
    return token;
  });

  masked = masked.split(/(<[^>]+>)/g).map(part => {
    if (!part) return part;
    if (part.startsWith("<")) return translateAttributes(part);
    if (part.includes("\u0000VXRU")) return part;
    return translateChunk(part);
  }).join("");

  masked = masked.replace(/\u0000VXRU(\d+)\u0000/g, (_, index) => protectedBlocks[Number(index)] || "");
  return masked;
}

function localizeRussianHtml(html, pathname = "/") {
  if (typeof html !== "string" || !/<html\b|<body\b|<!doctype\s+html/i.test(html)) return html;
  let out = String(html);
  out = out.replace(/<html\b([^>]*)\blang=("[^"]*"|'[^']*')([^>]*)>/i, `<html$1lang="${LOCALE}"$3>`);
  if (!/<html\b[^>]*\blang=/i.test(out)) out = out.replace(/<html\b/i, `<html lang="${LOCALE}"`);
  out = translateHtmlText(out);
  out = localizeSeoHosts(out, pathname);
  return out;
}

function installRussianLocalization(app) {
  app.use((req, res, next) => {
    const host = req.get?.("host") || req.headers?.host || req.headers?.["x-forwarded-host"] || "";
    const pathname = pathnameOf(req);
    if (!isRussianHost(host) || !isLocalizablePath(pathname)) return next();

    const send = res.send.bind(res);
    res.send = function sendRussian(body) {
      const type = String(res.getHeader?.("Content-Type") || "").toLowerCase();
      if (typeof body === "string" && (!type || type.includes("text/html") || type.includes("html"))) {
        body = localizeRussianHtml(body, pathname);
      }
      return send(body);
    };
    return next();
  });
}

function copyExpressStatics(target, source) {
  for (const key of Reflect.ownKeys(source)) {
    if (["length", "name", "prototype", "arguments", "caller"].includes(String(key))) continue;
    const descriptor = Object.getOwnPropertyDescriptor(source, key);
    if (descriptor) try { Object.defineProperty(target, key, descriptor); } catch (_) {}
  }
  Object.setPrototypeOf(target, Object.getPrototypeOf(source));
}

function wrapExpress(factory) {
  if (typeof factory !== "function" || factory.__vixaleRussianLocalizationWrapped) return factory;
  function wrapped(...args) {
    const app = factory(...args);
    installRussianLocalization(app);
    return app;
  }
  copyExpressStatics(wrapped, factory);
  Object.defineProperty(wrapped, "__vixaleRussianLocalizationWrapped", { value: true });
  return wrapped;
}

const originalLoad = Module._load;
Module._load = function vixaleRussianLocalizationModuleLoad(request, parent, isMain) {
  const loaded = originalLoad.call(this, request, parent, isMain);
  return request === "express" ? wrapExpress(loaded) : loaded;
};

module.exports = {
  RU_HOST,
  EN_HOST,
  LOCALE,
  PRIVATE_PREFIXES,
  TRANSLATIONS,
  normalizeHost,
  isRussianHost,
  pathnameOf,
  isLocalizablePath,
  translateChunk,
  translateAttributes,
  translateHtmlText,
  localizeSeoHosts,
  localizeRussianHtml,
  installRussianLocalization,
  wrapExpress,
};
