"use strict";
const assert=require("assert");
const {SYSTEMS_PATH,DAY_PATH,SWING_PATH,OPTIONS_PATH,STYLE_ID,PAGE_MARKER,refineTradingSystemsProductPage}=require("../website_trading_systems_product_refinement");
const base=`<!doctype html><html><head><title>Old Systems</title><link rel="canonical" href="https://www.vixale.com/old"></head><body><nav><div class="nav-links"><a class="vx-beginner-nav-link" href="/trading-guide">Beginner Guide</a><a class="vx-risk-management-nav-link" href="/risk-management">Risk Management</a><a href="/">Live System</a><a href="/trading-systems">Trading Systems</a><a href="#start-here">Start Here</a><a href="#services">Why It Makes Sense</a><a href="/pricing">7 Days Free</a><a href="/dashboard">Live Dashboard</a></div></nav><main><h1>old wall of text</h1><h2>Systems at a glance.</h2><div>Market Coverage</div></main><footer>Important disclosure</footer></body></html>`;
const hub=refineTradingSystemsProductPage(base,SYSTEMS_PATH);assert(hub.includes(`${PAGE_MARKER}="${SYSTEMS_PATH}"`));assert(hub.includes(`id="${STYLE_ID}"`));assert(hub.includes("Choose the type of system you want to explore."));assert(hub.includes(`href="${DAY_PATH}"`)&&hub.includes(`href="${SWING_PATH}"`)&&hub.includes(`href="${OPTIONS_PATH}"`));assert(!hub.includes("Systems at a glance.")&&!hub.includes("Market Coverage")&&!hub.includes("old wall of text"));assert(hub.includes('href="https://t.me/tradervip22">Telegram</a>'));assert(hub.includes("<title>Vixale | Trading Systems</title>"));
const day=refineTradingSystemsProductPage(base,DAY_PATH);assert(day.includes("Vixale Prime")&&day.includes("Vixale Edge"));assert(!day.includes("Options Straddles")&&!day.includes("Vixale Swing System"));assert(day.includes("<title>Vixale | Day Trading Systems</title>"));assert(day.includes(`href="https://www.vixale.com${DAY_PATH}"`));
const swing=refineTradingSystemsProductPage(base,SWING_PATH);assert(swing.includes("Vixale Swing System")&&swing.includes('href="/swing-leaders">View Swing Leaders</a>'));assert(!swing.includes("Vixale Prime")&&!swing.includes("Options Straddles"));
const options=refineTradingSystemsProductPage(base,OPTIONS_PATH);assert(options.includes("Options Straddles")&&options.includes('href="/dashboard">View Options Desk</a>'));assert(!options.includes('href="/options"')&&!options.includes("Vixale Prime")&&!options.includes("Vixale Swing System"));
assert.strictEqual(refineTradingSystemsProductPage(hub,SYSTEMS_PATH),hub);assert.strictEqual(refineTradingSystemsProductPage(base,"/"),base);console.log("Trading Systems four-page IA: PASS");
